import type { Resource } from "./types";

// Sample content so the whole site is visible before Supabase is connected.
// Once Supabase has real rows, lib/resources.ts reads from there instead.
export const SAMPLE_RESOURCES: Resource[] = [
  {
    slug: "ai-hook-vault",
    title: "The AI hook vault",
    description: "50 openers that stop the scroll, pulled from my best-performing videos.",
    whats_inside: ["50 plug-and-play hooks", "The 6 hook patterns that go viral", "How to adapt any hook to your niche"],
    category: "Hooks",
    cover_url: null,
    pdf_path: "ai-hook-vault.pdf",
    video_url: null,
    featured: true,
    published: true,
  },
  {
    slug: "founder-story-formula",
    title: "Founder story formula",
    description: "The exact structure behind every viral founder story edit I make.",
    whats_inside: ["The 4-act story spine", "Where to put the emotional turn", "A fill-in-the-blank template"],
    category: "Storytelling",
    cover_url: null,
    pdf_path: "founder-story-formula.pdf",
    video_url: null,
    featured: true,
    published: true,
  },
  {
    slug: "daily-content-engine",
    title: "Daily content engine",
    description: "The system I use to never run out of ideas, hooks, or scripts.",
    whats_inside: ["The idea capture workflow", "My AI prompt stack", "A weekly content calendar"],
    category: "Systems",
    cover_url: null,
    pdf_path: "daily-content-engine.pdf",
    video_url: null,
    featured: true,
    published: true,
  },
  {
    slug: "viral-script-template",
    title: "Viral script template",
    description: "A short-form script skeleton that keeps retention high to the last frame.",
    whats_inside: ["Hook → tension → payoff structure", "Pacing and cut markers", "Two worked examples"],
    category: "Scripts",
    cover_url: null,
    pdf_path: "viral-script-template.pdf",
    video_url: null,
    featured: false,
    published: true,
  },
  {
    slug: "ai-tool-stack",
    title: "My AI tool stack",
    description: "Every tool I actually use to research, write, edit, and ship content.",
    whats_inside: ["The full stack by stage", "What each tool is for", "Free vs paid picks"],
    category: "Tools",
    cover_url: null,
    pdf_path: "ai-tool-stack.pdf",
    video_url: null,
    featured: false,
    published: true,
  },
  {
    slug: "cold-dm-playbook",
    title: "Brand deal DM playbook",
    description: "The messages and rates I use to land paid collabs as a creator.",
    whats_inside: ["Outreach + reply scripts", "How I price collabs", "Red flags to walk away from"],
    category: "Growth",
    cover_url: null,
    pdf_path: "cold-dm-playbook.pdf",
    video_url: null,
    featured: false,
    published: true,
  },
];
