// Publishes the Summer 2027 Master List to the hub: uploads the PDF,
// seeds the resources row, and adds the metered-article content
// (article fragments generated by lead-magnets/2027-internships-master/gen_article.py).
// Run from ~/joshualarosa-ai:  node scripts/add_2027.mjs
import { createClient } from "@supabase/supabase-js";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import os from "node:os";

const ROOT = path.resolve(import.meta.dirname, "..");
const env = Object.fromEntries(
  readFileSync(path.join(ROOT, ".env.local"), "utf8").split("\n").filter((l) => l.includes("="))
    .map((l) => { const i = l.indexOf("="); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; })
);
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });

const SLUG = "summer-2027-internships";
const MAG = path.join(os.homedir(), "lead-magnets/2027-internships-master");

const teaser = readFileSync(path.join(MAG, "article_teaser.html"), "utf8");
const rest = readFileSync(path.join(MAG, "article_rest.html"), "utf8");

(async () => {
  const pdf = readFileSync(path.join(MAG, "pdf/2027-internships-master-guide.pdf"));
  const up = await sb.storage.from("pdfs").upload(`${SLUG}.pdf`, pdf, { contentType: "application/pdf", upsert: true });
  console.log("pdf upload:", up.error ? up.error.message : "ok");

  const row = {
    slug: SLUG,
    title: "Summer 2027 Internships: 160+ Open Roles With Direct Apply Links",
    description: "The Summer 2027 internship master list — 160+ open roles across banking, quant, software, consulting, accounting, and engineering with direct apply links. Including the five from the video, one paying $25,000 a month plus a $25,000 signing bonus.",
    whats_inside: [
      "The featured five (SpaceX, Anduril, JPMorgan, TikTok, D.E. Shaw)",
      "18 quant & trading roles — the money tier",
      "24 banking & investing roles, closing rolling",
      "16 software, data & product roles (Google 2027 is live)",
      "Consulting, accounting, engineering, construction, ops & legal",
      "The 2027 timeline + the after-you-apply playbook",
    ],
    category: "Career",
    cover_url: null,
    pdf_path: `${SLUG}.pdf`,
    video_url: null,
    featured: true,
    published: true,
  };
  const { error } = await sb.from("resources").upsert(row, { onConflict: "slug" });
  console.log("row upsert:", error ? error.message : "ok");

  const gcPath = path.join(ROOT, "lib", "guideContent.json");
  const gc = JSON.parse(readFileSync(gcPath, "utf8"));
  gc[SLUG] = { teaser, rest };
  writeFileSync(gcPath, JSON.stringify(gc, null, 1));
  console.log("guideContent.json updated; total entries:", Object.keys(gc).length);
})();
